import React from 'react';
import { MdDownload, MdPictureAsPdf, MdTableChart } from 'react-icons/md';

export default function Reports() {
    return (
        <div className="max-w-4xl mx-auto animate-fade-in relative pb-10 space-y-8">
            <div>
                <h1 className="text-3xl font-bold text-slate-800 mb-2">Analytics Reports</h1>
                <p className="text-slate-500">Generate and download standard performance reports for administrators or meetings.</p>
            </div>

            <div className="grid sm:grid-cols-2 gap-6">
                {/* Report Card 1 */}
                <div className="bg-white p-6 rounded-2xl shadow-sm border border-slate-200 hover:border-brand-blue transition-colors group">
                    <div className="w-12 h-12 bg-blue-50 text-brand-blue rounded-xl flex items-center justify-center mb-4">
                        <MdPictureAsPdf className="w-6 h-6" />
                    </div>
                    <h3 className="text-lg font-bold text-slate-800 mb-2">Weekly Class Summary</h3>
                    <p className="text-slate-500 text-sm mb-6 leading-relaxed">PDF report containing class averages, assignment completion rates, and an automated summary paragraph generated by Gemini.</p>
                    <button className="w-full text-brand-blue font-bold px-4 py-2 border-2 border-brand-blue rounded-lg flex items-center justify-center gap-2 group-hover:bg-brand-blue group-hover:text-white transition-colors">
                        <MdDownload className="w-5 h-5" /> Download PDF
                    </button>
                </div>

                {/* Report Card 2 */}
                <div className="bg-white p-6 rounded-2xl shadow-sm border border-slate-200 hover:border-brand-green transition-colors group">
                    <div className="w-12 h-12 bg-green-50 text-brand-green rounded-xl flex items-center justify-center mb-4">
                        <MdTableChart className="w-6 h-6" />
                    </div>
                    <h3 className="text-lg font-bold text-slate-800 mb-2">Raw Grading Data (CSV)</h3>
                    <p className="text-slate-500 text-sm mb-6 leading-relaxed">A complete spreadsheet of all student submissions, rubric scores, and raw outputs suitable for school legacy ERP systems.</p>
                    <button className="w-full text-brand-green font-bold px-4 py-2 border-2 border-brand-green rounded-lg flex items-center justify-center gap-2 group-hover:bg-brand-green group-hover:text-white transition-colors">
                        <MdDownload className="w-5 h-5" /> Export CSV
                    </button>
                </div>
            </div>
        </div>
    );
}